global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: python-metrics-monitoring
  honor_labels: true
  static_configs:
  - targets: ['python-metrics-monitoring:5000']