{
 "title": "Databrick-custom-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Databricks-CD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Last Update Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cd_last_status_boolean{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "ghe Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cd_last_status_boolean{}", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Success Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_request_success_total{}" }
   ]
  },
  {
   "title": "Failed Count",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "python_request_failed_total{}" }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Running DB Clusters",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_running_db_clusters{}" }
   ]
  }
 ]
}