apiVersion: v1
kind: Service
metadata:
  name: "python-custom-metrics-svc"
  labels:
    run: "python-custom-metrics"
spec:
  ports:
  - name: metrics
    port: 5000
    protocol: TCP
  selector:
    run: "python-custom-metrics"